### ISSUE TITLE
Most (all?) character tiddlers contain illegal field names

### ISSUE THREAD

**Issue by Marxsal** [mklauber/tw-5eSRD-Monsters#1]
I'm not a D&D user, but passing on a discovery per this conversation: 

https://groups.google.com/forum/#!topic/tiddlywiki/GCqPlEYSg7c

It appears that most or perhaps all of the tiddlers have a field name containing the illegal characters "" . This  has caused a conflict with at least one other plugin, and is likely to cause other problems as well.

Thanks!

**Comment by mklauber** [comment]
Fixed
